export interface DepartmentInfo {
  slug: string;
  trName: string;
  trDescription: string;
  enName: string;
  enDescription: string;
  arName: string;
  arDescription: string;
}

export const departmentDirectory: DepartmentInfo[] = [
  {
    slug: 'cardiology',
    trName: 'Kardiyoloji',
    trDescription: 'Kalp ve damar hastalıklarıyla ilgilenen tıp dalıdır.',
    enName: 'Cardiology',
    enDescription: 'Medical specialty dealing with heart and blood vessel diseases.',
    arName: 'أمراض القلب',
    arDescription: 'تخصص طبي يتعامل مع أمراض القلب والأوعية الدموية.',
  },
  {
    slug: 'dermatology',
    trName: 'Deri ve Zührevi Hastalıklar',
    trDescription: 'Cilt, saç, tırnak ve cinsel yolla bulaşan hastalıkları inceleyen tıp dalıdır.',
    enName: 'Dermatology',
    enDescription: 'Medical specialty dealing with skin, hair, nails, and sexually transmitted diseases.',
    arName: 'الأمراض الجلدية',
    arDescription: 'تخصص طبي يتعامل مع الجلد والشعر والأظافر والأمراض المنقولة جنسياً.',
  },
  {
    slug: 'dentistry',
    trName: 'Diş Hekimliği',
    trDescription: 'Ağız, diş ve çene sağlığı ile ilgilenen tıp dalıdır.',
    enName: 'Dentistry',
    enDescription: 'Medical specialty dealing with oral, dental, and jaw health.',
    arName: 'طب الأسنان',
    arDescription: 'تخصص طبي يتعامل مع صحة الفم والأسنان والفك.',
  },
  {
    slug: 'internal-medicine',
    trName: 'Dahiliye (İç Hastalıkları)',
    trDescription: 'Erişkinlerdeki iç organ hastalıklarını teşhis ve tedavi eden tıp dalıdır.',
    enName: 'Internal Medicine',
    enDescription: 'Medical specialty that diagnoses and treats internal organ diseases in adults.',
    arName: 'الطب الباطني',
    arDescription: 'تخصص طبي يشخص ويعالج أمراض الأعضاء الداخلية عند البالغين.',
  },
  {
    slug: 'neurology',
    trName: 'Nöroloji (Beyin ve Sinir Hastalıkları)',
    trDescription: 'Sinir sistemi hastalıklarını inceleyen tıp dalıdır.',
    enName: 'Neurology',
    enDescription: 'Medical specialty studying nervous system diseases.',
    arName: 'طب الأعصاب',
    arDescription: 'تخصص طبي يدرس أمراض الجهاز العصبي.',
  },
  {
    slug: 'orthopedics',
    trName: 'Ortopedi (Kemik Hastalıkları)',
    trDescription: 'Kas-iskelet sistemi hastalıkları ve yaralanmalarıyla ilgilenen tıp dalıdır.',
    enName: 'Orthopedics',
    enDescription: 'Medical specialty dealing with musculoskeletal system diseases and injuries.',
    arName: 'جراحة العظام',
    arDescription: 'تخصص طبي يتعامل مع أمراض وإصابات الجهاز العضلي الهيكلي.',
  },
  {
    slug: 'psychiatry',
    trName: 'Psikiyatri (Ruh Sağlığı)',
    trDescription: 'Ruh sağlığı ve davranış bozuklukları ile ilgilenen tıp dalıdır.',
    enName: 'Psychiatry',
    enDescription: 'Medical specialty dealing with mental health and behavioral disorders.',
    arName: 'الطب النفسي',
    arDescription: 'تخصص طبي يتعامل مع الصحة النفسية واضطرابات السلوك.',
  },
  {
    slug: 'pediatrics',
    trName: 'Pediatri (Çocuk Hastalıkları)',
    trDescription: 'Çocukların sağlığı ve hastalıkları ile ilgilenen tıp dalıdır.',
    enName: 'Pediatrics',
    enDescription: 'Medical specialty dealing with children\'s health and diseases.',
    arName: 'طب الأطفال',
    arDescription: 'تخصص طبي يتعامل مع صحة الأطفال وأمراضهم.',
  },
  {
    slug: 'gastroenterology',
    trName: 'Gastroenteroloji (Sindirim Sistemi)',
    trDescription: 'Sindirim sistemi hastalıkları ile ilgilenen tıp dalıdır.',
    enName: 'Gastroenterology',
    enDescription: 'Medical specialty dealing with digestive system diseases.',
    arName: 'أمراض الجهاز الهضمي',
    arDescription: 'تخصص طبي يتعامل مع أمراض الجهاز الهضمي.',
  },
  {
    slug: 'ophthalmology',
    trName: 'Göz Hastalıkları',
    trDescription: 'Göz sağlığı ve hastalıkları ile ilgilenen tıp dalıdır.',
    enName: 'Ophthalmology',
    enDescription: 'Medical specialty dealing with eye health and diseases.',
    arName: 'طب العيون',
    arDescription: 'تخصص طبي يتعامل مع صحة العين وأمراضها.',
  },
  {
    slug: 'ent',
    trName: 'Kulak Burun Boğaz (KBB)',
    trDescription: 'Kulak, burun, boğaz ve baş-boyun bölgesi hastalıkları ile ilgilenen tıp dalıdır.',
    enName: 'ENT (Ear, Nose, Throat)',
    enDescription: 'Medical specialty dealing with ear, nose, throat, and head-neck region diseases.',
    arName: 'الأذن والأنف والحنجرة',
    arDescription: 'تخصص طبي يتعامل مع أمراض الأذن والأنف والحنجرة ومنطقة الرأس والرقبة.',
  },
  {
    slug: 'urology',
    trName: 'Üroloji (İdrar Yolları)',
    trDescription: 'İdrar yolları ve erkek üreme organları hastalıkları ile ilgilenen tıp dalıdır.',
    enName: 'Urology',
    enDescription: 'Medical specialty dealing with urinary tract and male reproductive organ diseases.',
    arName: 'المسالك البولية',
    arDescription: 'تخصص طبي يتعامل مع أمراض المسالك البولية والأعضاء التناسلية الذكرية.',
  },
  {
    slug: 'gynecology',
    trName: 'Kadın Hastalıkları ve Doğum',
    trDescription: 'Kadın üreme sistemi hastalıkları ve gebelik ile ilgilenen tıp dalıdır.',
    enName: 'Gynecology and Obstetrics',
    enDescription: 'Medical specialty dealing with female reproductive system diseases and pregnancy.',
    arName: 'أمراض النساء والتوليد',
    arDescription: 'تخصص طبي يتعامل مع أمراض الجهاز التناسلي الأنثوي والحمل.',
  },
  {
    slug: 'general-surgery',
    trName: 'Genel Cerrahi',
    trDescription: 'Cerrahi müdahale gerektiren hastalıkların tedavisi ile ilgilenen tıp dalıdır.',
    enName: 'General Surgery',
    enDescription: 'Medical specialty dealing with treatment of diseases requiring surgical intervention.',
    arName: 'الجراحة العامة',
    arDescription: 'تخصص طبي يتعامل مع علاج الأمراض التي تتطلب التدخل الجراحي.',
  },
  {
    slug: 'endocrinology',
    trName: 'Endokrinoloji (Hormon Hastalıkları)',
    trDescription: 'Hormon ve metabolizma hastalıkları ile ilgilenen tıp dalıdır.',
    enName: 'Endocrinology',
    enDescription: 'Medical specialty dealing with hormone and metabolism diseases.',
    arName: 'الغدد الصماء',
    arDescription: 'تخصص طبي يتعامل مع أمراض الهرمونات والتمثيل الغذائي.',
  },
];
